version: "3.4"

services:
  newznab-tmux:
    build: 
      context: .
      dockerfile: Dockerfiles/newznab-tmux
      args:
        - APP_TZ=${APP_TZ}
    image: newznab/newznab-tmux:latest
    depends_on: 
      - db
    networks:
      - newznab_tmux_network
    volumes:
      - .env:/var/www/NNTmux/.env
      - ~/DockerInit.d/nginx-nntmux:/etc/nginx/sites-available/NNTMux
    ports:
      - 8081:80
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MANTICORE_HOST=${MANTICORE_HOST}
      - MANTICORE_PORT=${MANTICORE_PORT}
  db:
    build:
      context: .
      dockerfile: Dockerfiles/mariadb
      args:
        - DB_DATABASE=${DB_DATABASE}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
    image: newznab/mariadb
    networks:
      - newznab_tmux_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
networks:
  newznab_tmux_network:
    external:
      name: newznab_tmux_network
