B_HOST=${1-db}
DB_DATABASE=${2-nntmux}
DB_USERNAME=${3-newsie}
DB_PASSWORD=${4-changeme}

echo "CREATE DATABASE IF NOT EXISTS ${DB_DATABASE};";
echo "CREATE USER IF NOT EXISTS '${DB_USERNAME}' IDENTIFIED BY '${DB_PASSWORD}';";
echo "GRANT ALL ON ${DB_NAME}.* TO '${DB_USERNAME}'@'%';";
echo "GRANT ALL PRIVILEGES ON *.* TO '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWROD}' WITH GRANT OPTION;";
echo "flush privileges;"; 

echo "INSTALL SONAME 'ha_sphinx';";
