# DB_DATABASE=${1-nntmux}
# DB_USERNAME=${2-newsie}
# DB_PASSWORD=${3-changeme}
DB_DATABASE=${1}
DB_USERNAME=${2}
DB_PASSWORD=${3}

echo "CREATE DATABASE IF NOT EXISTS ${DB_DATABASE};";
echo "CREATE USER IF NOT EXISTS '${DB_USERNAME}' IDENTIFIED BY '${DB_PASSWORD}';";
echo "GRANT ALL ON ${DB_DATABASE}.* TO '${DB_USERNAME}'@'%';";
echo "GRANT ALL PRIVILEGES ON *.* TO '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWORD}' WITH GRANT OPTION;";
echo "flush privileges;"; 

echo "INSTALL SONAME 'ha_sphinx';";
