NEWZNAB_DB_HOST=${1-db}
NEWZNAB_DB_NAME=${2-nntmux}
NEWZNAB_DB_USERNAME=${3-newsie}
NEWZNAB_DB_PASSWORD=${4-changeme}

echo "CREATE DATABASE IF NOT EXISTS ${NEWZNAB_DB_NAME};";
echo "CREATE USER IF NOT EXISTS '${NEWZNAB_DB_USERNAME}' IDENTIFIED BY '${NEWZNAB_DB_PASSWORD}';";
echo "GRANT ALL ON ${NEWZNAB_DB_NAME}.* TO '${NEWZNAB_DB_USERNAME}'@'%';";
echo "GRANT ALL PRIVILEGES ON *.* TO '${NEWZNAB_DB_USERNAME}'@'%' IDENTIFIED BY '${NEWZNAB_DB_PASSWROD}' WITH GRANT OPTION;";
echo "flush privileges;"; 

echo "INSTALL SONAME 'ha_sphinx';";
